### ISSUE TITLE
Problem with mixed content (when Spotweb is hosted over SSL)

### ISSUE THREAD

**Issue by CptChaos** [Goeny/BootSpot#1]
Hello, 

First of all; this is a nice (bootstrap) template for Spotweb, I really love it and I hope more will follow your example!
I only have one issue at the moment. I am hosting my Spotweb over SSL and the stylesheets are externally loaded over HTTP. This gives me an error, because mixed content is disabled by default.
It would therefore be nice, if the template checks for SSL, to get the files over SSL (if available) or are self-hosted.

Many thanks in advance,
CptChaos

**Comment by Goeny** [comment]
At this point, the stylesheet is loaded externally from the bootswatch website.
This is a temporary measure because i am not sure yet which bootswatch stylesheet i want to use with this template.

I am thinking about a selectbox in which all bootswatch templates are available so you can switch within spotweb itself.

The stylesheets will be included in the template when the template is ready for the public.

**Comment by Goeny** [comment]
I have included all externally loaded .js and .css files.
Please try and let me know if this works for you.

**Comment by CptChaos** [comment]
Hello Goeny,

Thanks for the quick replies, it seems to be working now! :)

**Comment by Goeny** [comment]
Thank you for your feedback. Closing this issue.
